# Generated by Django 5.0.1 on 2024-02-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_phone',
            field=models.CharField(default='your_default_value_here', max_length=20),
        ),
    ]
