# Generated by Django 5.0.1 on 2024-02-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userdetails_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Normal', 'Normal')], max_length=20),
        ),
    ]
